# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FM

  target 'FMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FMUITests' do
    inherit! :search_paths
    # Pods for testing
  end


pod ‘Masonry’
pod ‘AFNetworking’
pod ‘YYModel’
pod ‘WMPageController’
pod ‘MJRefresh’
pod ‘BlocksKit’
pod ‘MBProgressHUD’
pod'SDCycleScrollView'

end
